// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/alchemy/list': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/alchemy/list.get').default>>>>
    }
    '/api/alchemy/refine': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/alchemy/refine.post').default>>>>
    }
    '/api/auth/login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/login.post').default>>>>
    }
    '/api/auth/me': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/me.get').default>>>>
    }
    '/api/auth/register': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/register.post').default>>>>
    }
    '/api/cultivate/breakthrough': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/cultivate/breakthrough.post').default>>>>
    }
    '/api/cultivate/progress': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/cultivate/progress.get').default>>>>
    }
    '/api/inventory': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/inventory.get').default>>>>
    }
    '/api/rankings': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/rankings.get').default>>>>
    }
    '/api/shop/buy': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/shop/buy.post').default>>>>
    }
    '/api/shop/items': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/shop/items.get').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}