// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2026/5/12 16:19:36
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
import cfg3 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/home/zeshuai007/claude/webgames/xianni-game/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/zeshuai007/claude/webgames/xianni-game/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/zeshuai007/claude/webgames/xianni-game/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/zeshuai007/claude/webgames/xianni-game/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/zeshuai007/claude/webgames/xianni-game/plugins/**/*.{js,ts,mjs}","/home/zeshuai007/claude/webgames/xianni-game/composables/**/*.{js,ts,mjs}","/home/zeshuai007/claude/webgames/xianni-game/utils/**/*.{js,ts,mjs}","/home/zeshuai007/claude/webgames/xianni-game/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/zeshuai007/claude/webgames/xianni-game/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/zeshuai007/claude/webgames/xianni-game/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/zeshuai007/claude/webgames/xianni-game/app.config.{js,ts,mjs}"]}},
{},
cfg2,
cfg3
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;